# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Fundament Research Institute <https://fundament.institute>

[package]
name = "nixui"
version = "0.1.0"
edition = "2024"

[dependencies]
nix-editor = "0.3.0"
feather-ui = { git = "https://github.com/Fundament-Software/feathergui", branch = "simplify" }
feather-macro = { git = "https://github.com/Fundament-Software/feathergui", branch = "simplify" }
